import numpy as np
import pandas as pd
from scipy.optimize import minimize
from scipy.special import gammaln


def mixed_effect_morphology_feature_tests(
    df_analysis,
    morphology_features=None,
    diagnosis_col="diagnosis_group",
    scan_col="scan_name",
    group_a="AD",
    group_b="100+",
    max_cells_per_scan=2000,
    random_state=42,
    apply_fdr=True,
):
    """
    Test morphology-feature differences between diagnosis groups with a
    random-intercept mixed-effects model.

    Plain-English model:
      feature_value = (overall baseline) + (AD vs 100+ effect) +
                      (scan-specific baseline offset) + noise

    Mathematical form (for one feature y_{ij}):
      y_{ij} = beta_0 + beta_1 * I[group_i = AD] + b_j + epsilon_{ij}
      b_j ~ Normal(0, sigma_scan^2), epsilon_{ij} ~ Normal(0, sigma^2)

    Why this helps:
      Cells from the same scan are correlated. A mixed model explicitly models
      that correlation via b_j (random intercept per scan), instead of treating
      all cells as independent.

    Parameters
    ----------
    df_analysis : pd.DataFrame
        Must contain diagnosis_col, scan_col, and morphology feature columns.
    morphology_features : list[str] | None
        Feature columns to test. If None, infer numeric columns and exclude
        obvious metadata.
    diagnosis_col : str
        Column with diagnosis labels.
    scan_col : str
        Column identifying scans (random-effect grouping variable).
    group_a, group_b : str
        Groups compared; reported effect is group_a - group_b.
    max_cells_per_scan : int | None
        Optional per-scan cap to keep fitting tractable on very large datasets.
        If None, use all rows.
    random_state : int
        RNG seed for optional subsampling.
    apply_fdr : bool
        If True, add Benjamini-Hochberg FDR q-values across features.

    Returns
    -------
    pd.DataFrame
        One row per feature with mixed-model effect estimate and uncertainty.
    """

    # Import inside the function so other utilities in this module can still be
    # used even if statsmodels is unavailable in a given environment.
    import statsmodels.formula.api as smf

    required_cols = {diagnosis_col, scan_col}
    missing = required_cols - set(df_analysis.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")

    # Keep only the two requested diagnosis groups for a clean binary contrast.
    df_work = df_analysis[df_analysis[diagnosis_col].isin([group_a, group_b])].copy()
    if df_work.empty:
        raise ValueError(f"No rows found for groups {group_a} and {group_b}")

    # Optional downsampling to keep mixed-model fitting computationally feasible.
    # This preserves scan-level structure by sampling *within each scan*.
    if max_cells_per_scan is not None:
        rng = np.random.default_rng(random_state)

        def _sample_scan(g):
            if len(g) <= max_cells_per_scan:
                return g
            idx = rng.choice(g.index.to_numpy(), size=max_cells_per_scan, replace=False)
            return g.loc[idx]

        df_work = (
            df_work.groupby(scan_col, group_keys=False)
            .apply(_sample_scan)
            .reset_index(drop=True)
        )

    if morphology_features is None:
        # Infer numeric candidate features and drop known metadata-like columns.
        inferred = df_work.select_dtypes(include=[np.number]).columns.tolist()
        exclude = {
            "tile_id",
            "x",
            "y",
            "centroid_x",
            "centroid_y",
            "hard_cluster",
        }
        morphology_features = [c for c in inferred if c not in exclude]

    # Parameter name generated by statsmodels for the diagnosis fixed effect.
    # We set group_b as reference, so coefficient means (group_a - group_b).
    effect_name = f"C({diagnosis_col}, Treatment(reference='{group_b}'))[T.{group_a}]"

    rows = []
    for feature in morphology_features:
        if feature not in df_work.columns:
            continue

        sub = df_work[[feature, diagnosis_col, scan_col]].dropna().copy()
        if sub.empty:
            continue

        # Need both groups and at least 2 scans for random-effect estimation.
        present_groups = set(sub[diagnosis_col].unique())
        if not ({group_a, group_b} <= present_groups):
            continue
        if sub[scan_col].nunique() < 2:
            continue

        # Mixed model with scan-level random intercept.
        # Plain English: each scan gets its own baseline offset.
        formula = f"{feature} ~ C({diagnosis_col}, Treatment(reference='{group_b}'))"

        try:
            model = smf.mixedlm(formula=formula, data=sub, groups=sub[scan_col], re_formula="1")
            result = model.fit(reml=False, method="lbfgs", maxiter=500, disp=False)

            coef = float(result.params.get(effect_name, np.nan))
            se = float(result.bse.get(effect_name, np.nan))
            z_stat = float(result.tvalues.get(effect_name, np.nan))
            p_val = float(result.pvalues.get(effect_name, np.nan))

            # Approximate 95% Wald CI for the fixed effect.
            ci_low = coef - 1.96 * se if pd.notna(se) else np.nan
            ci_high = coef + 1.96 * se if pd.notna(se) else np.nan

            # Estimated random-effect variance component for scan intercepts.
            scan_var = np.nan
            if result.cov_re is not None and result.cov_re.shape == (1, 1):
                scan_var = float(result.cov_re.iloc[0, 0])

            rows.append(
                {
                    "feature": feature,
                    "n_cells": int(len(sub)),
                    "n_scans": int(sub[scan_col].nunique()),
                    f"coef_{group_a}_minus_{group_b}": coef,
                    "se": se,
                    "z_stat": z_stat,
                    "p_value": p_val,
                    "ci_2.5%": ci_low,
                    "ci_97.5%": ci_high,
                    "scan_random_intercept_var": scan_var,
                    "converged": bool(getattr(result, "converged", False)),
                }
            )
        except Exception as exc:
            rows.append(
                {
                    "feature": feature,
                    "n_cells": int(len(sub)),
                    "n_scans": int(sub[scan_col].nunique()),
                    f"coef_{group_a}_minus_{group_b}": np.nan,
                    "se": np.nan,
                    "z_stat": np.nan,
                    "p_value": np.nan,
                    "ci_2.5%": np.nan,
                    "ci_97.5%": np.nan,
                    "scan_random_intercept_var": np.nan,
                    "converged": False,
                    "fit_error": str(exc),
                }
            )

    out = pd.DataFrame(rows)
    if out.empty:
        raise RuntimeError("No features were successfully evaluated by mixed-effects modeling.")

    if apply_fdr:
        from statsmodels.stats.multitest import multipletests

        valid = out["p_value"].notna()
        out["q_value_fdr_bh"] = np.nan
        if valid.any():
            _, qvals, _, _ = multipletests(out.loc[valid, "p_value"].to_numpy(), method="fdr_bh")
            out.loc[valid, "q_value_fdr_bh"] = qvals

    sort_col = "q_value_fdr_bh" if apply_fdr and "q_value_fdr_bh" in out.columns else "p_value"
    out = out.sort_values(sort_col, na_position="last").reset_index(drop=True)

    print("=== Mixed-effects feature test (random intercept by scan_name) ===")
    print(
        "Interpretation: coef > 0 means higher values in "
        f"{group_a} than {group_b} after accounting for scan-level variance."
    )
    print(out.to_string(index=False))

    return out

def dirichlet_scan_level_group_comparison(
    full_df,
    cluster_type="hard",                 # "hard" or "soft"
    diagnosis_col="diagnosis_group",
    group_a="AD",
    group_b="100+",
    n_boot=1000,
    random_state=42,
    eps=1e-10,
):
    """
    Dirichlet analysis on scan-level compositions.

    full_df must contain:
      - diagnosis_col (e.g., diagnosis_group)
      - columns like f"{cluster_type}_cluster_0", ..., f"{cluster_type}_cluster_{K-1}"

    Returns dict with:
      - group_fits: fitted Dirichlet parameters and implied moments per group
      - mean_diff: bootstrap summary for mean composition differences (group_a - group_b)
      - var_diff: bootstrap summary for Dirichlet-implied variance differences
      - concentration_diff: bootstrap summary for alpha0 difference
    """

    # -------- helpers --------
    def _cluster_cols(df, prefix):
        cols = [c for c in df.columns if c.startswith(prefix)]
        if not cols:
            raise ValueError(f"No columns found with prefix '{prefix}'")
        cols = sorted(cols, key=lambda s: int(s.split("_")[-1]))
        return cols

    def _prepare_X(df_sub, cols):
        X = df_sub[cols].to_numpy(dtype=float)
        if X.ndim != 2 or X.shape[1] < 2:
            raise ValueError("Need at least 2 cluster columns.")
        # clip and renormalize
        X = np.clip(X, eps, 1.0)
        X = X / X.sum(axis=1, keepdims=True)
        return X

    def _dirichlet_nll(log_alpha, X):
        alpha = np.exp(log_alpha)  # positivity
        a0 = alpha.sum()
        n = X.shape[0]
        ll = n * (gammaln(a0) - np.sum(gammaln(alpha))) + np.sum((alpha - 1.0) * np.log(X))
        return -ll

    def _dirichlet_init(X):
        # method-of-moments style init
        m = X.mean(axis=0)
        v = X.var(axis=0, ddof=1) if X.shape[0] > 1 else np.full_like(m, 1e-3)
        with np.errstate(divide="ignore", invalid="ignore"):
            a0_candidates = m * (1.0 - m) / np.maximum(v, 1e-12) - 1.0
        a0_candidates = a0_candidates[np.isfinite(a0_candidates) & (a0_candidates > 0)]
        a0 = np.median(a0_candidates) if len(a0_candidates) else 10.0
        alpha0 = np.maximum(m * a0, 1e-3)
        return alpha0

    def _fit_dirichlet(X):
        init_alpha = _dirichlet_init(X)
        res = minimize(
            _dirichlet_nll,
            x0=np.log(init_alpha),
            args=(X,),
            method="L-BFGS-B",
        )
        if not res.success:
            raise RuntimeError(f"Dirichlet fit failed: {res.message}")
        alpha = np.exp(res.x)
        a0 = alpha.sum()
        mu = alpha / a0
        var = (alpha * (a0 - alpha)) / (a0**2 * (a0 + 1.0))
        return alpha, a0, mu, var

    def _summarize_delta(samples, names, value_col):
        # samples: (B, K)
        rows = []
        for j, name in enumerate(names):
            d = samples[:, j]
            d = d[np.isfinite(d)]
            rows.append({
                "cluster": name,
                value_col: float(np.mean(d)),
                "ci_2.5%": float(np.quantile(d, 0.025)),
                "ci_97.5%": float(np.quantile(d, 0.975)),
                f"p_{group_a}_gt_{group_b}": float(np.mean(d > 0)),
            })
        out = pd.DataFrame(rows)
        out["abs_effect"] = out[value_col].abs()
        out = out.sort_values("abs_effect", ascending=False).drop(columns="abs_effect")
        return out

    # -------- data prep --------
    prefix = f"{cluster_type}_cluster_"
    cols = _cluster_cols(full_df, prefix)

    df_use = full_df[[diagnosis_col] + cols].dropna().copy()
    df_a = df_use[df_use[diagnosis_col] == group_a]
    df_b = df_use[df_use[diagnosis_col] == group_b]

    if len(df_a) == 0 or len(df_b) == 0:
        raise ValueError(f"Need rows for both groups: {group_a}, {group_b}")

    X_a = _prepare_X(df_a, cols)
    X_b = _prepare_X(df_b, cols)

    # -------- fit on original data --------
    alpha_a, a0_a, mu_a, var_a = _fit_dirichlet(X_a)
    alpha_b, a0_b, mu_b, var_b = _fit_dirichlet(X_b)

    group_fits = pd.DataFrame({
        "group": [group_a, group_b],
        "n_scans": [len(X_a), len(X_b)],
        "alpha0_concentration": [a0_a, a0_b],
        "mean_entropy": [
            float(-np.sum(mu_a * np.log(mu_a + 1e-12))),
            float(-np.sum(mu_b * np.log(mu_b + 1e-12))),
        ],
    })

    # cluster-level fit summaries
    fit_detail = []
    for j, c in enumerate(cols):
        fit_detail.append({
            "cluster": c,
            f"mean_{group_a}": float(mu_a[j]),
            f"mean_{group_b}": float(mu_b[j]),
            "delta_mean_A_minus_B": float(mu_a[j] - mu_b[j]),
            f"dirichlet_var_{group_a}": float(var_a[j]),
            f"dirichlet_var_{group_b}": float(var_b[j]),
            "delta_var_A_minus_B": float(var_a[j] - var_b[j]),
        })
    fit_detail = pd.DataFrame(fit_detail)

    # -------- bootstrap uncertainty --------
    rng = np.random.default_rng(random_state)

    delta_mu_samples = []
    delta_var_samples = []
    delta_a0_samples = []

    for _ in range(n_boot):
        ia = rng.integers(0, len(X_a), len(X_a))
        ib = rng.integers(0, len(X_b), len(X_b))
        Xa_bs = X_a[ia]
        Xb_bs = X_b[ib]

        try:
            _, a0a_bs, mua_bs, vara_bs = _fit_dirichlet(Xa_bs)
            _, a0b_bs, mub_bs, varb_bs = _fit_dirichlet(Xb_bs)
        except Exception:
            continue

        delta_mu_samples.append(mua_bs - mub_bs)
        delta_var_samples.append(vara_bs - varb_bs)
        delta_a0_samples.append(a0a_bs - a0b_bs)

    if len(delta_mu_samples) < max(100, int(0.2 * n_boot)):
        raise RuntimeError(
            f"Too few successful bootstrap fits ({len(delta_mu_samples)}/{n_boot}). "
            "Try reducing n_boot or checking data quality."
        )

    delta_mu_samples = np.asarray(delta_mu_samples)      # (B_ok, K)
    delta_var_samples = np.asarray(delta_var_samples)    # (B_ok, K)
    delta_a0_samples = np.asarray(delta_a0_samples)      # (B_ok,)

    mean_diff = _summarize_delta(
        delta_mu_samples,
        names=cols,
        value_col=f"delta_mean_{group_a}_minus_{group_b}"
    )

    var_diff = _summarize_delta(
        delta_var_samples,
        names=cols,
        value_col=f"delta_dirichlet_var_{group_a}_minus_{group_b}"
    )

    concentration_diff = pd.DataFrame([{
        "metric": "alpha0_concentration",
        f"delta_{group_a}_minus_{group_b}": float(np.mean(delta_a0_samples)),
        "ci_2.5%": float(np.quantile(delta_a0_samples, 0.025)),
        "ci_97.5%": float(np.quantile(delta_a0_samples, 0.975)),
        f"p_{group_a}_gt_{group_b}": float(np.mean(delta_a0_samples > 0)),
    }])

    # -------- print concise summaries --------
    print(f"=== Dirichlet fit summary ({cluster_type}) ===")
    print(group_fits.to_string(index=False))
    print("\n=== Cluster mean differences (Dirichlet, bootstrap) ===")
    print(mean_diff.to_string(index=False))
    print("\n=== Cluster variance differences (Dirichlet-implied, bootstrap) ===")
    print(var_diff.to_string(index=False))
    print("\n=== Concentration difference (alpha0; higher = lower between-scan variance) ===")
    print(concentration_diff.to_string(index=False))

    return {
        "group_fits": group_fits,
        "fit_detail": fit_detail,
        "mean_diff": mean_diff,
        "var_diff": var_diff,
        "concentration_diff": concentration_diff,
        "bootstrap_successful": int(len(delta_mu_samples)),
        "cluster_cols": cols,
    }



def mixed_effect_morphology_feature_tests_bambi(
    df_analysis,
    morphology_features=None,
    diagnosis_col="diagnosis_group",
    scan_col="scan_name",
    group_a="AD",
    group_b="100+",
    max_cells_per_scan=2000,
    random_state=42,
    apply_fdr=True,
):
    """
    Bayesian mixed-effects feature test using Bambi + PyMC.

    Model (per feature):
        feature ~ diagnosis_group + (1 | scan_name)

    Interpretation:
      - coef_AD_minus_100+ > 0 means higher values in AD than 100+,
        accounting for scan-level random intercept variance.
      - ci_2.5% / ci_97.5% are 95% posterior credible intervals.
      - p_AD_gt_100+ is posterior probability that AD effect > 0.

    Notes:
      - This is Bayesian, so "p_value" here is a pseudo two-sided tail probability:
            p_value = 2 * min(P(effect > 0), P(effect < 0))
        (included mainly to keep output structure similar to your existing pipeline).
    """
    import numpy as np
    import pandas as pd
    import arviz as az
    import bambi as bmb

    required_cols = {diagnosis_col, scan_col}
    missing = required_cols - set(df_analysis.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")

    # Keep only the two requested diagnosis groups
    df_work = df_analysis[df_analysis[diagnosis_col].isin([group_a, group_b])].copy()
    if df_work.empty:
        raise ValueError(f"No rows found for groups {group_a} and {group_b}")

    # Ensure reference coding: group_b baseline, group_a contrast
    df_work[diagnosis_col] = pd.Categorical(
        df_work[diagnosis_col],
        categories=[group_b, group_a],
        ordered=True,
    )

    # Optional per-scan subsampling
    if max_cells_per_scan is not None:
        rng = np.random.default_rng(random_state)

        def _sample_scan(g):
            if len(g) <= max_cells_per_scan:
                return g
            idx = rng.choice(g.index.to_numpy(), size=max_cells_per_scan, replace=False)
            return g.loc[idx]

        df_work = (
            df_work.groupby(scan_col, group_keys=False)
            .apply(_sample_scan)
            .reset_index(drop=True)
        )

    # Feature inference if not provided
    if morphology_features is None:
        inferred = df_work.select_dtypes(include=[np.number]).columns.tolist()
        exclude = {
            "tile_id",
            "x",
            "y",
            "centroid_x",
            "centroid_y",
            "hard_cluster",
        }
        morphology_features = [c for c in inferred if c not in exclude]

    rows = []

    for feature in morphology_features:
        if feature not in df_work.columns:
            continue

        sub = df_work[[feature, diagnosis_col, scan_col]].dropna().copy()
        if sub.empty:
            continue

        present_groups = set(sub[diagnosis_col].astype(str).unique())
        if not ({group_a, group_b} <= present_groups):
            continue
        if sub[scan_col].nunique() < 2:
            continue

        formula = f"{feature} ~ {diagnosis_col} + (1|{scan_col})"

        try:
            # Gaussian family to mirror your previous linear mixed model setup
            model = bmb.Model(formula=formula, data=sub, family="gaussian")

            idata = model.fit(
                draws=1000,
                tune=1000,
                chains=2,
                cores=2,
                random_seed=random_state,
                target_accept=0.95,
                progressbar=False,
            )

            posterior_vars = list(idata.posterior.data_vars)

            # Find the diagnosis contrast term robustly
            # Common names look like: diagnosis_group[AD]
            effect_candidates = [
                v for v in posterior_vars
                if diagnosis_col in v and str(group_a) in v
            ]
            if not effect_candidates:
                raise RuntimeError(
                    f"Could not find posterior diagnosis effect term for {feature}. "
                    f"Posterior vars: {posterior_vars}"
                )
            effect_var = sorted(effect_candidates)[0]

            effect_samples = np.asarray(idata.posterior[effect_var]).reshape(-1)
            coef = float(effect_samples.mean())
            se = float(effect_samples.std(ddof=1))

            hdi = az.hdi(effect_samples, hdi_prob=0.95)
            ci_low = float(hdi[0])
            ci_high = float(hdi[1])

            p_ad_gt = float((effect_samples > 0).mean())
            p_val = float(2.0 * min(p_ad_gt, 1.0 - p_ad_gt))  # pseudo 2-sided tail prob

            # Try to recover random-intercept SD for scan and convert to variance
            scan_var = np.nan
            scan_sd_candidates = [
                v for v in posterior_vars
                if scan_col in v and ("sigma" in v.lower() or "sd" in v.lower())
            ]
            if scan_sd_candidates:
                sd_samples = np.asarray(idata.posterior[sorted(scan_sd_candidates)[0]]).reshape(-1)
                scan_var = float((sd_samples ** 2).mean())

            # Divergences as a Bayesian fit-quality flag
            n_div = 0
            if hasattr(idata, "sample_stats") and "diverging" in idata.sample_stats:
                n_div = int(np.asarray(idata.sample_stats["diverging"]).sum())

            rows.append(
                {
                    "feature": feature,
                    "n_cells": int(len(sub)),
                    "n_scans": int(sub[scan_col].nunique()),
                    f"coef_{group_a}_minus_{group_b}": coef,
                    "se": se,
                    "z_stat": np.nan,  # not directly used in this Bayesian workflow
                    "p_value": p_val,
                    "ci_2.5%": ci_low,
                    "ci_97.5%": ci_high,
                    f"p_{group_a}_gt_{group_b}": p_ad_gt,
                    "scan_random_intercept_var": scan_var,
                    "converged": bool(n_div == 0),
                    "n_divergences": n_div,
                }
            )

        except Exception as exc:
            rows.append(
                {
                    "feature": feature,
                    "n_cells": int(len(sub)),
                    "n_scans": int(sub[scan_col].nunique()),
                    f"coef_{group_a}_minus_{group_b}": np.nan,
                    "se": np.nan,
                    "z_stat": np.nan,
                    "p_value": np.nan,
                    "ci_2.5%": np.nan,
                    "ci_97.5%": np.nan,
                    f"p_{group_a}_gt_{group_b}": np.nan,
                    "scan_random_intercept_var": np.nan,
                    "converged": False,
                    "n_divergences": np.nan,
                    "fit_error": str(exc),
                }
            )

    out = pd.DataFrame(rows)
    if out.empty:
        raise RuntimeError("No features were successfully evaluated by Bayesian mixed-effects modeling.")

    if apply_fdr:
        from statsmodels.stats.multitest import multipletests

        valid = out["p_value"].notna()
        out["q_value_fdr_bh"] = np.nan
        if valid.any():
            _, qvals, _, _ = multipletests(out.loc[valid, "p_value"].to_numpy(), method="fdr_bh")
            out.loc[valid, "q_value_fdr_bh"] = qvals

    sort_col = "q_value_fdr_bh" if apply_fdr and "q_value_fdr_bh" in out.columns else "p_value"
    out = out.sort_values(sort_col, na_position="last").reset_index(drop=True)

    print("=== Bayesian mixed-effects feature test (Bambi + PyMC; random intercept by scan_name) ===")
    print(
        "Interpretation: coef > 0 means higher values in "
        f"{group_a} than {group_b} after accounting for scan-level variance.\n"
        f"Also inspect p_{group_a}_gt_{group_b} and credible intervals."
    )
    print(out.to_string(index=False))

    return out
