import numpy as np
import pandas as pd
from scipy.optimize import minimize
from scipy.special import gammaln


def mixed_effect_morphology_feature_tests(
    df_analysis,
    morphology_features=None,
    scan_features=None,
    diagnosis_col="diagnosis_group",
    scan_col="scan_name",
    group_a="AD",
    group_b="100+",
    max_cells_per_scan=None,
    random_state=42,
    apply_fdr=True,
):
    """
    Build scan-level means and test morphology-feature differences between
    diagnosis groups while adjusting for scan-level covariates.

    Step 1 (aggregation):
      Collapse cell-level rows to one row per scan_name:
      - morphology features: mean within scan
      - diagnosis_group + scan_features: one value per scan (first value,
        after consistency checks)

    Step 2 (model per feature at scan level):
      y_s = beta_0 + beta_1 * I[group_s = AD] + sum_k gamma_k * X_{s,k} + epsilon_s
      where X_{s,k} are scan_features covariates (e.g., Sex).

    Why this helps:
      Aggregating to scan level avoids cell-level pseudo-replication and makes
      diagnosis inference happen at the scan/patient unit.

    Parameters
    ----------
    df_analysis : pd.DataFrame
        Must contain diagnosis_col, scan_col, and morphology feature columns.
    morphology_features : list[str] | None
        Feature columns to test. If None, infer numeric columns and exclude
        obvious metadata.
    scan_features : list[str] | None
        Scan-level covariates to include in the model (e.g., ['Sex']).
        These are carried into the scan-level dataframe without averaging.
    diagnosis_col : str
        Column with diagnosis labels.
    scan_col : str
        Column identifying scans (random-effect grouping variable).
    group_a, group_b : str
        Groups compared; reported effect is group_a - group_b.
    max_cells_per_scan : int | None
        Optional per-scan cap to keep fitting tractable on very large datasets.
        If None, use all rows.
    random_state : int
        RNG seed for optional subsampling.
    apply_fdr : bool
        If True, add Benjamini-Hochberg FDR q-values across features.

    Returns
    -------
    dict
        {
          'scan_level_df': one row per scan with mean morphology + scan features,
          'model_results': one row per feature with adjusted diagnosis effect.
        }
    """

    # Import inside the function so other utilities in this module can still be
    # used even if statsmodels is unavailable in a given environment.
    import statsmodels.formula.api as smf

    if scan_features is None:
        scan_features = []

    required_cols = {diagnosis_col, scan_col, *scan_features}
    missing = required_cols - set(df_analysis.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")

    # Keep only the two requested diagnosis groups for a clean binary contrast.
    df_work = df_analysis[df_analysis[diagnosis_col].isin([group_a, group_b])].copy()
    if df_work.empty:
        raise ValueError(f"No rows found for groups {group_a} and {group_b}")

    # max_cells_per_scan is kept for backward-compatible signature.
    # After scan-level aggregation it is not used.
    _ = max_cells_per_scan
    _ = random_state

    if morphology_features is None:
        # Infer numeric candidate features and drop known metadata-like columns.
        inferred = df_work.select_dtypes(include=[np.number]).columns.tolist()
        exclude = {
            "tile_id",
            "x",
            "y",
            "centroid_x",
            "centroid_y",
            "hard_cluster",
        }
        morphology_features = [c for c in inferred if c not in exclude]

    # Build scan-level table:
    # - mean morphology per scan
    # - diagnosis + scan_features carried over per scan
    agg_map = {f: "mean" for f in morphology_features if f in df_work.columns}
    for c in [diagnosis_col] + list(scan_features):
        if c in df_work.columns:
            agg_map[c] = "first"

    scan_level_df = (
        df_work.groupby(scan_col, as_index=False)
        .agg(agg_map)
    )

    # Basic consistency checks: diagnosis and scan_features should be constant
    # within each scan in most datasets.
    check_cols = [diagnosis_col] + list(scan_features)
    for c in check_cols:
        if c not in df_work.columns:
            continue
        nunique_per_scan = df_work.groupby(scan_col)[c].nunique(dropna=False)
        if (nunique_per_scan > 1).any():
            n_bad = int((nunique_per_scan > 1).sum())
            print(
                f"Warning: column '{c}' has >1 distinct value in {n_bad} scans; "
                "using first value during scan-level aggregation."
            )

    # Parameter name generated by statsmodels for the diagnosis fixed effect.
    # We set group_b as reference, so coefficient means (group_a - group_b).
    effect_name = f"C({diagnosis_col}, Treatment(reference='{group_b}'))[T.{group_a}]"

    rows = []
    for feature in morphology_features:
        if feature not in scan_level_df.columns:
            continue

        model_cols = [feature, diagnosis_col] + list(scan_features)
        sub = scan_level_df[model_cols].dropna().copy()
        if sub.empty:
            continue

        # Need both groups for diagnosis contrast.
        present_groups = set(sub[diagnosis_col].unique())
        if not ({group_a, group_b} <= present_groups):
            continue

        # Scan-level regression adjusted for scan_features.
        # Categorical covariates use C(...), numeric covariates stay numeric.
        cov_terms = []
        for c in scan_features:
            if c not in sub.columns:
                continue
            if pd.api.types.is_numeric_dtype(sub[c]):
                cov_terms.append(c)
            else:
                cov_terms.append(f"C({c})")

        rhs_terms = [f"C({diagnosis_col}, Treatment(reference='{group_b}'))"] + cov_terms
        formula = f"{feature} ~ {' + '.join(rhs_terms)}"

        try:
            model = smf.ols(formula=formula, data=sub)
            result = model.fit()

            coef = float(result.params.get(effect_name, np.nan))
            se = float(result.bse.get(effect_name, np.nan))
            z_stat = float(result.tvalues.get(effect_name, np.nan))
            p_val = float(result.pvalues.get(effect_name, np.nan))

            # Approximate 95% Wald CI for the fixed effect.
            ci_low = coef - 1.96 * se if pd.notna(se) else np.nan
            ci_high = coef + 1.96 * se if pd.notna(se) else np.nan

            rows.append(
                {
                    "feature": feature,
                    "n_scans": int(len(sub)),
                    f"coef_{group_a}_minus_{group_b}": coef,
                    "se": se,
                    "z_stat": z_stat,
                    "p_value": p_val,
                    "ci_2.5%": ci_low,
                    "ci_97.5%": ci_high,
                    "converged": bool(getattr(result, "converged", False)),
                }
            )
        except Exception as exc:
            rows.append(
                {
                    "feature": feature,
                    "n_scans": int(len(sub)),
                    f"coef_{group_a}_minus_{group_b}": np.nan,
                    "se": np.nan,
                    "z_stat": np.nan,
                    "p_value": np.nan,
                    "ci_2.5%": np.nan,
                    "ci_97.5%": np.nan,
                    "converged": False,
                    "fit_error": str(exc),
                }
            )

    out = pd.DataFrame(rows)
    if out.empty:
        raise RuntimeError("No features were successfully evaluated by mixed-effects modeling.")

    if apply_fdr:
        from statsmodels.stats.multitest import multipletests

        valid = out["p_value"].notna()
        out["q_value_fdr_bh"] = np.nan
        if valid.any():
            _, qvals, _, _ = multipletests(out.loc[valid, "p_value"].to_numpy(), method="fdr_bh")
            out.loc[valid, "q_value_fdr_bh"] = qvals

    sort_col = "q_value_fdr_bh" if apply_fdr and "q_value_fdr_bh" in out.columns else "p_value"
    out = out.sort_values(sort_col, na_position="last").reset_index(drop=True)

    print("=== Scan-level feature test (diagnosis adjusted for scan_features) ===")
    print(f"Scan-level dataframe shape: {scan_level_df.shape}")
    print(
        "Interpretation: coef > 0 means higher values in "
        f"{group_a} than {group_b} after adjusting for scan_features: {scan_features}."
    )
    print(out.to_string(index=False))

    return {
        "scan_level_df": scan_level_df,
        "model_results": out,
    }

def dirichlet_scan_level_group_comparison(
    full_df,
    cluster_type="hard",                 # "hard" or "soft"
    diagnosis_col="diagnosis_group",
    group_a="AD",
    group_b="100+",
    n_boot=1000,
    random_state=42,
    eps=1e-10,
):
    """
    Dirichlet analysis on scan-level compositions.

    full_df must contain:
      - diagnosis_col (e.g., diagnosis_group)
      - columns like f"{cluster_type}_cluster_0", ..., f"{cluster_type}_cluster_{K-1}"

    Returns dict with:
      - group_fits: fitted Dirichlet parameters and implied moments per group
      - mean_diff: bootstrap summary for mean composition differences (group_a - group_b)
      - var_diff: bootstrap summary for Dirichlet-implied variance differences
      - concentration_diff: bootstrap summary for alpha0 difference
    """

    # -------- helpers --------
    def _cluster_cols(df, prefix):
        cols = [c for c in df.columns if c.startswith(prefix)]
        if not cols:
            raise ValueError(f"No columns found with prefix '{prefix}'")
        cols = sorted(cols, key=lambda s: int(s.split("_")[-1]))
        return cols

    def _prepare_X(df_sub, cols):
        X = df_sub[cols].to_numpy(dtype=float)
        if X.ndim != 2 or X.shape[1] < 2:
            raise ValueError("Need at least 2 cluster columns.")
        # clip and renormalize
        X = np.clip(X, eps, 1.0)
        X = X / X.sum(axis=1, keepdims=True)
        return X

    def _dirichlet_nll(log_alpha, X):
        alpha = np.exp(log_alpha)  # positivity
        a0 = alpha.sum()
        n = X.shape[0]
        ll = n * (gammaln(a0) - np.sum(gammaln(alpha))) + np.sum((alpha - 1.0) * np.log(X))
        return -ll

    def _dirichlet_init(X):
        # method-of-moments style init
        m = X.mean(axis=0)
        v = X.var(axis=0, ddof=1) if X.shape[0] > 1 else np.full_like(m, 1e-3)
        with np.errstate(divide="ignore", invalid="ignore"):
            a0_candidates = m * (1.0 - m) / np.maximum(v, 1e-12) - 1.0
        a0_candidates = a0_candidates[np.isfinite(a0_candidates) & (a0_candidates > 0)]
        a0 = np.median(a0_candidates) if len(a0_candidates) else 10.0
        alpha0 = np.maximum(m * a0, 1e-3)
        return alpha0

    def _fit_dirichlet(X):
        init_alpha = _dirichlet_init(X)
        res = minimize(
            _dirichlet_nll,
            x0=np.log(init_alpha),
            args=(X,),
            method="L-BFGS-B",
        )
        if not res.success:
            raise RuntimeError(f"Dirichlet fit failed: {res.message}")
        alpha = np.exp(res.x)
        a0 = alpha.sum()
        mu = alpha / a0
        var = (alpha * (a0 - alpha)) / (a0**2 * (a0 + 1.0))
        return alpha, a0, mu, var

    def _summarize_delta(samples, names, value_col):
        # samples: (B, K)
        rows = []
        for j, name in enumerate(names):
            d = samples[:, j]
            d = d[np.isfinite(d)]
            rows.append({
                "cluster": name,
                value_col: float(np.mean(d)),
                "ci_2.5%": float(np.quantile(d, 0.025)),
                "ci_97.5%": float(np.quantile(d, 0.975)),
                f"p_{group_a}_gt_{group_b}": float(np.mean(d > 0)),
            })
        out = pd.DataFrame(rows)
        out["abs_effect"] = out[value_col].abs()
        out = out.sort_values("abs_effect", ascending=False).drop(columns="abs_effect")
        return out

    # -------- data prep --------
    prefix = f"{cluster_type}_cluster_"
    cols = _cluster_cols(full_df, prefix)

    df_use = full_df[[diagnosis_col] + cols].dropna().copy()
    df_a = df_use[df_use[diagnosis_col] == group_a]
    df_b = df_use[df_use[diagnosis_col] == group_b]

    if len(df_a) == 0 or len(df_b) == 0:
        raise ValueError(f"Need rows for both groups: {group_a}, {group_b}")

    X_a = _prepare_X(df_a, cols)
    X_b = _prepare_X(df_b, cols)

    # -------- fit on original data --------
    alpha_a, a0_a, mu_a, var_a = _fit_dirichlet(X_a)
    alpha_b, a0_b, mu_b, var_b = _fit_dirichlet(X_b)

    group_fits = pd.DataFrame({
        "group": [group_a, group_b],
        "n_scans": [len(X_a), len(X_b)],
        "alpha0_concentration": [a0_a, a0_b],
        "mean_entropy": [
            float(-np.sum(mu_a * np.log(mu_a + 1e-12))),
            float(-np.sum(mu_b * np.log(mu_b + 1e-12))),
        ],
    })

    # cluster-level fit summaries
    fit_detail = []
    for j, c in enumerate(cols):
        fit_detail.append({
            "cluster": c,
            f"mean_{group_a}": float(mu_a[j]),
            f"mean_{group_b}": float(mu_b[j]),
            "delta_mean_A_minus_B": float(mu_a[j] - mu_b[j]),
            f"dirichlet_var_{group_a}": float(var_a[j]),
            f"dirichlet_var_{group_b}": float(var_b[j]),
            "delta_var_A_minus_B": float(var_a[j] - var_b[j]),
        })
    fit_detail = pd.DataFrame(fit_detail)

    # -------- bootstrap uncertainty --------
    rng = np.random.default_rng(random_state)

    delta_mu_samples = []
    delta_var_samples = []
    delta_a0_samples = []

    for _ in range(n_boot):
        ia = rng.integers(0, len(X_a), len(X_a))
        ib = rng.integers(0, len(X_b), len(X_b))
        Xa_bs = X_a[ia]
        Xb_bs = X_b[ib]

        try:
            _, a0a_bs, mua_bs, vara_bs = _fit_dirichlet(Xa_bs)
            _, a0b_bs, mub_bs, varb_bs = _fit_dirichlet(Xb_bs)
        except Exception:
            continue

        delta_mu_samples.append(mua_bs - mub_bs)
        delta_var_samples.append(vara_bs - varb_bs)
        delta_a0_samples.append(a0a_bs - a0b_bs)

    if len(delta_mu_samples) < max(100, int(0.2 * n_boot)):
        raise RuntimeError(
            f"Too few successful bootstrap fits ({len(delta_mu_samples)}/{n_boot}). "
            "Try reducing n_boot or checking data quality."
        )

    delta_mu_samples = np.asarray(delta_mu_samples)      # (B_ok, K)
    delta_var_samples = np.asarray(delta_var_samples)    # (B_ok, K)
    delta_a0_samples = np.asarray(delta_a0_samples)      # (B_ok,)

    mean_diff = _summarize_delta(
        delta_mu_samples,
        names=cols,
        value_col=f"delta_mean_{group_a}_minus_{group_b}"
    )

    var_diff = _summarize_delta(
        delta_var_samples,
        names=cols,
        value_col=f"delta_dirichlet_var_{group_a}_minus_{group_b}"
    )

    concentration_diff = pd.DataFrame([{
        "metric": "alpha0_concentration",
        f"delta_{group_a}_minus_{group_b}": float(np.mean(delta_a0_samples)),
        "ci_2.5%": float(np.quantile(delta_a0_samples, 0.025)),
        "ci_97.5%": float(np.quantile(delta_a0_samples, 0.975)),
        f"p_{group_a}_gt_{group_b}": float(np.mean(delta_a0_samples > 0)),
    }])

    # -------- print concise summaries --------
    print(f"=== Dirichlet fit summary ({cluster_type}) ===")
    print(group_fits.to_string(index=False))
    print("\n=== Cluster mean differences (Dirichlet, bootstrap) ===")
    print(mean_diff.to_string(index=False))
    print("\n=== Cluster variance differences (Dirichlet-implied, bootstrap) ===")
    print(var_diff.to_string(index=False))
    print("\n=== Concentration difference (alpha0; higher = lower between-scan variance) ===")
    print(concentration_diff.to_string(index=False))

    return {
        "group_fits": group_fits,
        "fit_detail": fit_detail,
        "mean_diff": mean_diff,
        "var_diff": var_diff,
        "concentration_diff": concentration_diff,
        "bootstrap_successful": int(len(delta_mu_samples)),
        "cluster_cols": cols,
    }
